FROM ruby:3.3-bookworm AS builder

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  nodejs \
  git \
  && rm -rf /var/lib/apt/lists/*

RUN gem install bundler jekyll

WORKDIR /app

COPY Gemfile ./

RUN bundle lock || true \
 && bundle config set without 'development test' \
 && bundle install

COPY . .

RUN JEKYLL_ENV=production \
    bundle exec jekyll build


FROM nginx:1.29-alpine-slim

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/_site /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
